<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1709207234468' stop='1709207239225'>
    <name>test/UAT_Cognito/AuthService_Login.test.js</name>
    <title>test/UAT_Cognito/AuthService_Login.test.js</title>
    <test-cases>
        <test-case start='1709207234468' status='passed' stop='1709207235339'>
            <name>API Success</name>
            <title>API Success</title>
            <labels>
                <label name='testId' value='API Endpoint-/services/invoker/cognito/signin-dev'/>
            </labels>
            <parameters/>
            <steps>
                <step start='1709207234469' status='passed' stop='1709207235336'>
                    <name>Values passed:"{\"username\":\"title@bluelandtitle.com\",\"password\":\"460@Bergen\"}"</name>
                    <title>Values passed:"{\"username\":\"title@bluelandtitle.com\",\"password\":\"460@Bergen\"}"</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <description type='text'>Response message from API:{"body":"An error occurred (NotAuthorizedException) when calling the InitiateAuth operation: Incorrect username or password.","statusCode":500,"headers":{"Content-Type":"application/json"}}</description>
        </test-case>
        <test-case start='1709207235339' status='passed' stop='1709207236077'>
            <name>Wrong username</name>
            <title>Wrong username</title>
            <labels>
                <label name='testId' value='API Endpoint-/services/invoker/cognito/signin-dev'/>
            </labels>
            <parameters/>
            <steps>
                <step start='1709207235339' status='passed' stop='1709207236077'>
                    <name>Values passed:"{\"username\":\"tititle@bluelandtitle.com\",\"password\":\"460@Bergen\"}"</name>
                    <title>Values passed:"{\"username\":\"tititle@bluelandtitle.com\",\"password\":\"460@Bergen\"}"</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <description type='text'>Response message from API:{"body":"An error occurred (UserNotFoundException) when calling the InitiateAuth operation: User does not exist.","statusCode":500,"headers":{"Content-Type":"application/json"}}</description>
        </test-case>
        <test-case start='1709207236077' status='passed' stop='1709207237346'>
            <name>Wrong password</name>
            <title>Wrong password</title>
            <labels>
                <label name='testId' value='API Endpoint-/services/invoker/cognito/signin-dev'/>
            </labels>
            <parameters/>
            <steps>
                <step start='1709207236078' status='passed' stop='1709207237345'>
                    <name>Values passed:"{\"username\":\"title@bluelandtitle.com\",\"password\":\"46sdsd460@Bergen\"}"</name>
                    <title>Values passed:"{\"username\":\"title@bluelandtitle.com\",\"password\":\"46sdsd460@Bergen\"}"</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <description type='text'>Response message from API:{"body":"An error occurred (NotAuthorizedException) when calling the InitiateAuth operation: Incorrect username or password.","statusCode":500,"headers":{"Content-Type":"application/json"}}</description>
        </test-case>
        <test-case start='1709207237346' status='passed' stop='1709207238480'>
            <name>Wrong username and password</name>
            <title>Wrong username and password</title>
            <labels>
                <label name='testId' value='API Endpoint-/services/invoker/cognito/signin-dev'/>
            </labels>
            <parameters/>
            <steps>
                <step start='1709207237346' status='passed' stop='1709207238480'>
                    <name>Values passed:"{\"username\":\"tititle@bluelandtitle.com\",\"password\":\"46sdsd460@Bergen\"}"</name>
                    <title>Values passed:"{\"username\":\"tititle@bluelandtitle.com\",\"password\":\"46sdsd460@Bergen\"}"</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <description type='text'>Response message from API:{"body":"An error occurred (UserNotFoundException) when calling the InitiateAuth operation: User does not exist.","statusCode":500,"headers":{"Content-Type":"application/json"}}</description>
        </test-case>
        <test-case start='1709207238481' status='passed' stop='1709207239224'>
            <name>Plain text received as response</name>
            <title>Plain text received as response</title>
            <labels>
                <label name='testId' value='API Endpoint-/services/invoker/cognito/signin-dev'/>
            </labels>
            <parameters/>
            <steps>
                <step start='1709207238482' status='passed' stop='1709207239224'>
                    <name>Values passed:"{}"</name>
                    <title>Values passed:"{}"</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <description type='text'>Response message from API:{"error":"Username and Password Required","status_code":200}</description>
        </test-case>
    </test-cases>
</ns2:test-suite>